// Code generated by protoc-gen-go. DO NOT EDIT.
// source: boice.proto

package boice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Version              int32       `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Locktime             int32       `protobuf:"varint,2,opt,name=locktime,proto3" json:"locktime,omitempty"`
	Vin                  []*TxInput  `protobuf:"bytes,3,rep,name=vin,proto3" json:"vin,omitempty"`
	Vout                 []*TxOutput `protobuf:"bytes,4,rep,name=vout,proto3" json:"vout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_b97c19a98afaab4c, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetLocktime() int32 {
	if m != nil {
		return m.Locktime
	}
	return 0
}

func (m *Transaction) GetVin() []*TxInput {
	if m != nil {
		return m.Vin
	}
	return nil
}

func (m *Transaction) GetVout() []*TxOutput {
	if m != nil {
		return m.Vout
	}
	return nil
}

type TxOutput struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	ScriptPubKey         string   `protobuf:"bytes,2,opt,name=scriptPubKey,proto3" json:"scriptPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutput) Reset()         { *m = TxOutput{} }
func (m *TxOutput) String() string { return proto.CompactTextString(m) }
func (*TxOutput) ProtoMessage()    {}
func (*TxOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b97c19a98afaab4c, []int{1}
}

func (m *TxOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutput.Unmarshal(m, b)
}
func (m *TxOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutput.Marshal(b, m, deterministic)
}
func (m *TxOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutput.Merge(m, src)
}
func (m *TxOutput) XXX_Size() int {
	return xxx_messageInfo_TxOutput.Size(m)
}
func (m *TxOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutput proto.InternalMessageInfo

func (m *TxOutput) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TxOutput) GetScriptPubKey() string {
	if m != nil {
		return m.ScriptPubKey
	}
	return ""
}

type TxInput struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout                 int32    `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	ScriptSig            string   `protobuf:"bytes,3,opt,name=scriptSig,proto3" json:"scriptSig,omitempty"`
	Sequence             int64    `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxInput) Reset()         { *m = TxInput{} }
func (m *TxInput) String() string { return proto.CompactTextString(m) }
func (*TxInput) ProtoMessage()    {}
func (*TxInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b97c19a98afaab4c, []int{2}
}

func (m *TxInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInput.Unmarshal(m, b)
}
func (m *TxInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInput.Marshal(b, m, deterministic)
}
func (m *TxInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInput.Merge(m, src)
}
func (m *TxInput) XXX_Size() int {
	return xxx_messageInfo_TxInput.Size(m)
}
func (m *TxInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInput.DiscardUnknown(m)
}

var xxx_messageInfo_TxInput proto.InternalMessageInfo

func (m *TxInput) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *TxInput) GetVout() int32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *TxInput) GetScriptSig() string {
	if m != nil {
		return m.ScriptSig
	}
	return ""
}

func (m *TxInput) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type Block struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	PrevHash             []byte   `protobuf:"bytes,3,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	Data                 [][]byte `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_b97c19a98afaab4c, []int{3}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *Block) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BlockChain struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockChain) Reset()         { *m = BlockChain{} }
func (m *BlockChain) String() string { return proto.CompactTextString(m) }
func (*BlockChain) ProtoMessage()    {}
func (*BlockChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_b97c19a98afaab4c, []int{4}
}

func (m *BlockChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockChain.Unmarshal(m, b)
}
func (m *BlockChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockChain.Marshal(b, m, deterministic)
}
func (m *BlockChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockChain.Merge(m, src)
}
func (m *BlockChain) XXX_Size() int {
	return xxx_messageInfo_BlockChain.Size(m)
}
func (m *BlockChain) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockChain.DiscardUnknown(m)
}

var xxx_messageInfo_BlockChain proto.InternalMessageInfo

func (m *BlockChain) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "boice.Transaction")
	proto.RegisterType((*TxOutput)(nil), "boice.TxOutput")
	proto.RegisterType((*TxInput)(nil), "boice.TxInput")
	proto.RegisterType((*Block)(nil), "boice.Block")
	proto.RegisterType((*BlockChain)(nil), "boice.BlockChain")
}

func init() { proto.RegisterFile("boice.proto", fileDescriptor_b97c19a98afaab4c) }

var fileDescriptor_b97c19a98afaab4c = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0xea, 0xa4, 0x3f, 0xdb, 0xe8, 0xfb, 0x24, 0x8b, 0x83, 0x85, 0x38, 0x44, 0x81, 0x43,
	0x4f, 0x3d, 0x94, 0x37, 0x00, 0x0e, 0x20, 0x0e, 0x20, 0xd3, 0x17, 0x70, 0x52, 0x8b, 0x5a, 0x6d,
	0xed, 0x10, 0xdb, 0x51, 0x79, 0x05, 0x9e, 0x1a, 0xed, 0xa6, 0x4d, 0xc5, 0x6d, 0x67, 0x76, 0x34,
	0xb3, 0x1e, 0xc3, 0xbc, 0x72, 0xa6, 0xd6, 0xcb, 0xa6, 0x75, 0xc1, 0xf1, 0x8c, 0x40, 0xf9, 0x93,
	0xc0, 0x7c, 0xdd, 0x2a, 0xeb, 0x55, 0x1d, 0x8c, 0xb3, 0x5c, 0xc0, 0xa4, 0xd3, 0xad, 0x37, 0xce,
	0x8a, 0xa4, 0x48, 0x16, 0x99, 0x3c, 0x43, 0x7e, 0x0d, 0xd3, 0xbd, 0xab, 0x77, 0xc1, 0x1c, 0xb4,
	0x18, 0xd1, 0x6a, 0xc0, 0xbc, 0x00, 0xd6, 0x19, 0x2b, 0x58, 0xc1, 0x16, 0xf3, 0xd5, 0xbf, 0x65,
	0x9f, 0xb3, 0x3e, 0xbe, 0xd8, 0x26, 0x06, 0x89, 0x2b, 0x7e, 0x0b, 0x69, 0xe7, 0x62, 0x10, 0x29,
	0x49, 0xfe, 0x0f, 0x92, 0xb7, 0x18, 0x50, 0x43, 0xcb, 0xf2, 0x09, 0xa6, 0x67, 0x86, 0x5f, 0x41,
	0xd6, 0xa9, 0x7d, 0xd4, 0x74, 0xc6, 0x48, 0xf6, 0x80, 0x97, 0x90, 0xfb, 0xba, 0x35, 0x4d, 0x78,
	0x8f, 0xd5, 0xab, 0xfe, 0xa6, 0x43, 0x66, 0xf2, 0x0f, 0x57, 0xee, 0x60, 0x72, 0x8a, 0xe6, 0x1c,
	0xd2, 0x70, 0x34, 0x1b, 0xf2, 0x98, 0x49, 0x9a, 0x91, 0xa3, 0x4b, 0xfa, 0x37, 0xd0, 0xcc, 0x6f,
	0x60, 0xd6, 0x5b, 0x7c, 0x98, 0x4f, 0xc1, 0x48, 0x7c, 0x21, 0xf0, 0xe5, 0x5e, 0x7f, 0x45, 0x6d,
	0x6b, 0x2d, 0xd2, 0x22, 0x59, 0x30, 0x39, 0xe0, 0xd2, 0x40, 0xf6, 0x80, 0x35, 0xa0, 0x05, 0x56,
	0xe1, 0x83, 0x3a, 0x34, 0x94, 0xc7, 0xe4, 0x85, 0xc0, 0xd0, 0xad, 0xf2, 0x5b, 0x0a, 0xcd, 0x25,
	0xcd, 0x68, 0xdb, 0xb4, 0xba, 0x7b, 0x46, 0x9e, 0x11, 0x3f, 0x60, 0xd4, 0x6f, 0x54, 0x50, 0x54,
	0x57, 0x2e, 0x69, 0x2e, 0x57, 0x00, 0x14, 0xf5, 0xb8, 0x55, 0xc6, 0xf2, 0x3b, 0x18, 0x57, 0x88,
	0xbc, 0x48, 0xa8, 0xd2, 0xfc, 0x54, 0x29, 0x49, 0xe4, 0x69, 0x57, 0x8d, 0xe9, 0xb3, 0xef, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x54, 0x31, 0x89, 0xfb, 0x01, 0x00, 0x00,
}
